### ISSUE TITLE
Resource Bundle doesn't work with doctrine entities

### ISSUE THREAD

**Issue by mamazu** [Sylius/SyliusResourceBundle#111]
Given the following configuration
```yml
sylius_resource:
    app.store:
        classes:
            model: 'App\Entity\Store'
            factory: 'App\Factory\Store'
            repository: 'App\Repository\StoreRepository'
```

On the update action it loads the entity through a doctrine mapping and returns the proxy object with which it then tries to construct a default form type. For this it tries to load the model but fails because for the Proxy class `Proxies\__CG__\App\Entity\Store` there is no model registered. In Sylius this problem doesn't seem to show up because it takes the `data_class` from the form which is set in most cases.

Is this correct or is some other part of the Sylius magic failing because I am testing this when it is not part of a Sylius project.

**Comment by vvasiloi** [comment]
Your configuration is wrong.

**Comment by Roshyo** [comment]
What Vvasiloi is pointing out it that you're missing a line :

```
sylius_resource:
    resources:
        app.store:
            classes:
                model: 'App\Entity\Store'
                factory: 'App\Factory\Store'
                repository: 'App\Repository\StoreRepository'
```

**Comment by mamazu** [comment]
Ups copied it wrong. It's like that.

**Comment by Roshyo** [comment]
Are you sure you always use your entites via factories and repositories ? And never with a new() or something else ?

**Comment by mamazu** [comment]
Yes, but this is not the problem the problem is the update action where no object is "created" with a factory but with doctrine.

**Comment by vvasiloi** [comment]
The update action is looking for an existing object using the repository, it's not creating a new one.

**Comment by mamazu** [comment]
Correct and doctrine produces and this is the proxy object which is the problem.

**Comment by vvasiloi** [comment]
You're most likely doing something wrong, because the resource bundle works primarly with Doctrine ORM entities. Give more details about what you're doing and what went wrong, including errors if any.

**Comment by mamazu** [comment]
The error is the following:
<details>
  <summary>Stack trace</summary>
<pre>
<code>
{
  "error": {
    "code": 500,
    "message": "Internal Server Error",
    "exception": [
      {
        "message": "Resource with model class \"Proxies\\__CG__\\App\\Entity\\Store\" does not exist.",
        "class": "InvalidArgumentException",
        "trace": [
          {
            "namespace": "",
            "short_class": "",
            "class": "",
            "type": "",
            "function": "",
            "file": "\/var\/www\/htdocs\/vendor\/sylius\/resource-bundle\/src\/Component\/Metadata\/Registry.php",
            "line": 52,
            "args": []
          },
          {
            "namespace": "Sylius\\Component\\Resource\\Metadata",
            "short_class": "Registry",
            "class": "Sylius\\Component\\Resource\\Metadata\\Registry",
            "type": "->",
            "function": "getByClass",
            "file": "\/var\/www\/htdocs\/src\/Registry\/Registry.php",
            "line": 52,
            "args": [
              [
                "string",
                "Proxies\\__CG__\\App\\Entity\\Store"
              ]
            ]
          },
          {
            "namespace": "App\\Registry",
            "short_class": "Registry",
            "class": "App\\Registry\\Registry",
            "type": "->",
            "function": "getByClass",
            "file": "\/var\/www\/htdocs\/vendor\/sylius\/resource-bundle\/src\/Bundle\/Form\/Type\/DefaultResourceType.php",
            "line": 41,
            "args": [
              [
                "string",
                "Proxies\\__CG__\\App\\Entity\\Store"
              ]
            ]
          },
          {
            "namespace": "Sylius\\Bundle\\ResourceBundle\\Form\\Type",
            "short_class": "DefaultResourceType",
            "class": "Sylius\\Bundle\\ResourceBundle\\Form\\Type\\DefaultResourceType",
            "type": "->",
            "function": "buildForm",
            "file": "\/var\/www\/htdocs\/vendor\/symfony\/form\/ResolvedFormType.php",
            "line": 126,
            "args": [
              [
                "object",
                "Symfony\\Component\\Form\\FormBuilder"
              ],
              [
                "array",
                {
                  "block_name": [
                    "null",
                    null
                  ],
                  "disabled": [
                    "boolean",
                    false
                  ],
                  "label": [
                    "null",
                    null
                  ],
                  "label_format": [
                    "null",
                    null
                  ],
                  "label_translation_parameters": [
                    "array",
                    []
                  ],
                  "attr_translation_parameters": [
                    "array",
                    []
                  ],
                  "translation_domain": [
                    "null",
                    null
                  ],
                  "auto_initialize": [
                    "boolean",
                    true
                  ],
                  "trim": [
                    "boolean",
                    true
                  ],
                  "required": [
                    "boolean",
                    true
                  ],
                  "property_path": [
                    "null",
                    null
                  ],
                  "mapped": [
                    "boolean",
                    true
                  ],
                  "by_reference": [
                    "boolean",
                    true
                  ],
                  "inherit_data": [
                    "boolean",
                    false
                  ],
                  "compound": [
                    "boolean",
                    true
                  ],
                  "method": [
                    "string",
                    "POST"
                  ],
                  "action": [
                    "string",
                    ""
                  ],
                  "post_max_size_message": [
                    "string",
                    "The uploaded file was too large. Please try to upload a smaller file."
                  ],
                  "allow_file_upload": [
                    "boolean",
                    false
                  ],
                  "help_translation_parameters": [
                    "array",
                    []
                  ],
                  "error_mapping": [
                    "array",
                    []
                  ],
                  "invalid_message": [
                    "string",
                    "This value is not valid."
                  ],
                  "invalid_message_parameters": [
                    "array",
                    []
                  ],
                  "allow_extra_fields": [
                    "boolean",
                    false
                  ],
                  "extra_fields_message": [
                    "string",
                    "This form should not contain extra fields."
                  ],
                  "csrf_field_name": [
                    "string",
                    "_token"
                  ],
                  "csrf_message": [
                    "string",
                    "The CSRF token is invalid. Please try to resubmit the form."
                  ],
                  "csrf_token_manager": [
                    "object",
                    "Symfony\\Component\\Security\\Csrf\\CsrfTokenManager"
                  ],
                  "csrf_token_id": [
                    "null",
                    null
                  ],
                  "block_prefix": [
                    "null",
                    null
                  ],
                  "attr": [
                    "array",
                    []
                  ],
                  "data": [
                    "object",
                    "Proxies\\__CG__\\App\\Entity\\Store"
                  ],
                  "data_class": [
                    "string",
                    "Proxies\\__CG__\\App\\Entity\\Store"
                  ],
                  "empty_data": [
                    "object",
                    "Closure"
                  ],
                  "error_bubbling": [
                    "boolean",
                    true
                  ],
                  "label_attr": [
                    "array",
                    []
                  ],
                  "upload_max_size_message": [
                    "object",
                    "Closure"
                  ],
                  "help": [
                    "null",
                    null
                  ],
                  "help_attr": [
                    "array",
                    []
                  ],
                  "help_html": [
                    "boolean",
                    false
                  ],
                  "validation_groups": [
                    "null",
                    null
                  ],
                  "constraints": [
                    "array",
                    []
                  ],
                  "csrf_protection": [
                    "boolean",
                    false
                  ]
                }
              ]
            ]
          },
          {
            "namespace": "Symfony\\Component\\Form",
            "short_class": "ResolvedFormType",
            "class": "Symfony\\Component\\Form\\ResolvedFormType",
            "type": "->",
            "function": "buildForm",
            "file": "\/var\/www\/htdocs\/vendor\/symfony\/form\/Extension\/DataCollector\/Proxy\/ResolvedTypeDataCollectorProxy.php",
            "line": 95,
            "args": [
              [
                "object",
                "Symfony\\Component\\Form\\FormBuilder"
              ],
              [
                "array",
                {
                  "block_name": [
                    "null",
                    null
                  ],
                  "disabled": [
                    "boolean",
                    false
                  ],
                  "label": [
                    "null",
                    null
                  ],
                  "label_format": [
                    "null",
                    null
                  ],
                  "label_translation_parameters": [
                    "array",
                    []
                  ],
                  "attr_translation_parameters": [
                    "array",
                    []
                  ],
                  "translation_domain": [
                    "null",
                    null
                  ],
                  "auto_initialize": [
                    "boolean",
                    true
                  ],
                  "trim": [
                    "boolean",
                    true
                  ],
                  "required": [
                    "boolean",
                    true
                  ],
                  "property_path": [
                    "null",
                    null
                  ],
                  "mapped": [
                    "boolean",
                    true
                  ],
                  "by_reference": [
                    "boolean",
                    true
                  ],
                  "inherit_data": [
                    "boolean",
                    false
                  ],
                  "compound": [
                    "boolean",
                    true
                  ],
                  "method": [
                    "string",
                    "POST"
                  ],
                  "action": [
                    "string",
                    ""
                  ],
                  "post_max_size_message": [
                    "string",
                    "The uploaded file was too large. Please try to upload a smaller file."
                  ],
                  "allow_file_upload": [
                    "boolean",
                    false
                  ],
                  "help_translation_parameters": [
                    "array",
                    []
                  ],
                  "error_mapping": [
                    "array",
                    []
                  ],
                  "invalid_message": [
                    "string",
                    "This value is not valid."
                  ],
                  "invalid_message_parameters": [
                    "array",
                    []
                  ],
                  "allow_extra_fields": [
                    "boolean",
                    false
                  ],
                  "extra_fields_message": [
                    "string",
                    "This form should not contain extra fields."
                  ],
                  "csrf_field_name": [
                    "string",
                    "_token"
                  ],
                  "csrf_message": [
                    "string",
                    "The CSRF token is invalid. Please try to resubmit the form."
                  ],
                  "csrf_token_manager": [
                    "object",
                    "Symfony\\Component\\Security\\Csrf\\CsrfTokenManager"
                  ],
                  "csrf_token_id": [
                    "null",
                    null
                  ],
                  "block_prefix": [
                    "null",
                    null
                  ],
                  "attr": [
                    "array",
                    []
                  ],
                  "data": [
                    "object",
                    "Proxies\\__CG__\\App\\Entity\\Store"
                  ],
                  "data_class": [
                    "string",
                    "Proxies\\__CG__\\App\\Entity\\Store"
                  ],
                  "empty_data": [
                    "object",
                    "Closure"
                  ],
                  "error_bubbling": [
                    "boolean",
                    true
                  ],
                  "label_attr": [
                    "array",
                    []
                  ],
                  "upload_max_size_message": [
                    "object",
                    "Closure"
                  ],
                  "help": [
                    "null",
                    null
                  ],
                  "help_attr": [
                    "array",
                    []
                  ],
                  "help_html": [
                    "boolean",
                    false
                  ],
                  "validation_groups": [
                    "null",
                    null
                  ],
                  "constraints": [
                    "array",
                    []
                  ],
                  "csrf_protection": [
                    "boolean",
                    false
                  ]
                }
              ]
            ]
          },
          {
            "namespace": "Symfony\\Component\\Form\\Extension\\DataCollector\\Proxy",
            "short_class": "ResolvedTypeDataCollectorProxy",
            "class": "Symfony\\Component\\Form\\Extension\\DataCollector\\Proxy\\ResolvedTypeDataCollectorProxy",
            "type": "->",
            "function": "buildForm",
            "file": "\/var\/www\/htdocs\/vendor\/symfony\/form\/FormFactory.php",
            "line": 80,
            "args": [
              [
                "object",
                "Symfony\\Component\\Form\\FormBuilder"
              ],
              [
                "array",
                {
                  "block_name": [
                    "null",
                    null
                  ],
                  "disabled": [
                    "boolean",
                    false
                  ],
                  "label": [
                    "null",
                    null
                  ],
                  "label_format": [
                    "null",
                    null
                  ],
                  "label_translation_parameters": [
                    "array",
                    []
                  ],
                  "attr_translation_parameters": [
                    "array",
                    []
                  ],
                  "translation_domain": [
                    "null",
                    null
                  ],
                  "auto_initialize": [
                    "boolean",
                    true
                  ],
                  "trim": [
                    "boolean",
                    true
                  ],
                  "required": [
                    "boolean",
                    true
                  ],
                  "property_path": [
                    "null",
                    null
                  ],
                  "mapped": [
                    "boolean",
                    true
                  ],
                  "by_reference": [
                    "boolean",
                    true
                  ],
                  "inherit_data": [
                    "boolean",
                    false
                  ],
                  "compound": [
                    "boolean",
                    true
                  ],
                  "method": [
                    "string",
                    "POST"
                  ],
                  "action": [
                    "string",
                    ""
                  ],
                  "post_max_size_message": [
                    "string",
                    "The uploaded file was too large. Please try to upload a smaller file."
                  ],
                  "allow_file_upload": [
                    "boolean",
                    false
                  ],
                  "help_translation_parameters": [
                    "array",
                    []
                  ],
                  "error_mapping": [
                    "array",
                    []
                  ],
                  "invalid_message": [
                    "string",
                    "This value is not valid."
                  ],
                  "invalid_message_parameters": [
                    "array",
                    []
                  ],
                  "allow_extra_fields": [
                    "boolean",
                    false
                  ],
                  "extra_fields_message": [
                    "string",
                    "This form should not contain extra fields."
                  ],
                  "csrf_field_name": [
                    "string",
                    "_token"
                  ],
                  "csrf_message": [
                    "string",
                    "The CSRF token is invalid. Please try to resubmit the form."
                  ],
                  "csrf_token_manager": [
                    "object",
                    "Symfony\\Component\\Security\\Csrf\\CsrfTokenManager"
                  ],
                  "csrf_token_id": [
                    "null",
                    null
                  ],
                  "block_prefix": [
                    "null",
                    null
                  ],
                  "attr": [
                    "array",
                    []
                  ],
                  "data": [
                    "object",
                    "Proxies\\__CG__\\App\\Entity\\Store"
                  ],
                  "data_class": [
                    "string",
                    "Proxies\\__CG__\\App\\Entity\\Store"
                  ],
                  "empty_data": [
                    "object",
                    "Closure"
                  ],
                  "error_bubbling": [
                    "boolean",
                    true
                  ],
                  "label_attr": [
                    "array",
                    []
                  ],
                  "upload_max_size_message": [
                    "object",
                    "Closure"
                  ],
                  "help": [
                    "null",
                    null
                  ],
                  "help_attr": [
                    "array",
                    []
                  ],
                  "help_html": [
                    "boolean",
                    false
                  ],
                  "validation_groups": [
                    "null",
                    null
                  ],
                  "constraints": [
                    "array",
                    []
                  ],
                  "csrf_protection": [
                    "boolean",
                    false
                  ]
                }
              ]
            ]
          },
          {
            "namespace": "Symfony\\Component\\Form",
            "short_class": "FormFactory",
            "class": "Symfony\\Component\\Form\\FormFactory",
            "type": "->",
            "function": "createNamedBuilder",
            "file": "\/var\/www\/htdocs\/vendor\/symfony\/form\/FormFactory.php",
            "line": 38,
            "args": [
              [
                "string",
                ""
              ],
              [
                "object",
                "Symfony\\Component\\Form\\Extension\\DataCollector\\Proxy\\ResolvedTypeDataCollectorProxy"
              ],
              [
                "object",
                "Proxies\\__CG__\\App\\Entity\\Store"
              ],
              [
                "array",
                {
                  "csrf_protection": [
                    "boolean",
                    false
                  ],
                  "data": [
                    "object",
                    "Proxies\\__CG__\\App\\Entity\\Store"
                  ]
                }
              ]
            ]
          },
          {
            "namespace": "Symfony\\Component\\Form",
            "short_class": "FormFactory",
            "class": "Symfony\\Component\\Form\\FormFactory",
            "type": "->",
            "function": "createNamed",
            "file": "\/var\/www\/htdocs\/vendor\/sylius\/resource-bundle\/src\/Bundle\/Controller\/ResourceFormFactory.php",
            "line": 42,
            "args": [
              [
                "string",
                ""
              ],
              [
                "string",
                "Sylius\\Bundle\\ResourceBundle\\Form\\Type\\DefaultResourceType"
              ],
              [
                "object",
                "Proxies\\__CG__\\App\\Entity\\Store"
              ],
              [
                "array",
                {
                  "csrf_protection": [
                    "boolean",
                    false
                  ]
                }
              ]
            ]
          },
          {
            "namespace": "Sylius\\Bundle\\ResourceBundle\\Controller",
            "short_class": "ResourceFormFactory",
            "class": "Sylius\\Bundle\\ResourceBundle\\Controller\\ResourceFormFactory",
            "type": "->",
            "function": "create",
            "file": "\/var\/www\/htdocs\/vendor\/sylius\/resource-bundle\/src\/Bundle\/Controller\/ResourceController.php",
            "line": 256,
            "args": [
              [
                "object",
                "Sylius\\Bundle\\ResourceBundle\\Controller\\RequestConfiguration"
              ],
              [
                "object",
                "Proxies\\__CG__\\App\\Entity\\Store"
              ]
            ]
          },
          {
            "namespace": "Sylius\\Bundle\\ResourceBundle\\Controller",
            "short_class": "ResourceController",
            "class": "Sylius\\Bundle\\ResourceBundle\\Controller\\ResourceController",
            "type": "->",
            "function": "updateAction",
            "file": "\/var\/www\/htdocs\/vendor\/symfony\/http-kernel\/HttpKernel.php",
            "line": 151,
            "args": [
              [
                "object",
                "Symfony\\Component\\HttpFoundation\\Request"
              ]
            ]
          },
          {
            "namespace": "Symfony\\Component\\HttpKernel",
            "short_class": "HttpKernel",
            "class": "Symfony\\Component\\HttpKernel\\HttpKernel",
            "type": "->",
            "function": "handleRaw",
            "file": "\/var\/www\/htdocs\/vendor\/symfony\/http-kernel\/HttpKernel.php",
            "line": 68,
            "args": [
              [
                "object",
                "Symfony\\Component\\HttpFoundation\\Request"
              ],
              [
                "integer",
                1
              ]
            ]
          },
          {
            "namespace": "Symfony\\Component\\HttpKernel",
            "short_class": "HttpKernel",
            "class": "Symfony\\Component\\HttpKernel\\HttpKernel",
            "type": "->",
            "function": "handle",
            "file": "\/var\/www\/htdocs\/vendor\/symfony\/http-kernel\/Kernel.php",
            "line": 198,
            "args": [
              [
                "object",
                "Symfony\\Component\\HttpFoundation\\Request"
              ],
              [
                "integer",
                1
              ],
              [
                "boolean",
                true
              ]
            ]
          },
          {
            "namespace": "Symfony\\Component\\HttpKernel",
            "short_class": "Kernel",
            "class": "Symfony\\Component\\HttpKernel\\Kernel",
            "type": "->",
            "function": "handle",
            "file": "\/var\/www\/htdocs\/vendor\/symfony\/http-kernel\/Client.php",
            "line": 68,
            "args": [
              [
                "object",
                "Symfony\\Component\\HttpFoundation\\Request"
              ],
              [
                "integer",
                1
              ],
              [
                "boolean",
                true
              ]
            ]
          },
          {
            "namespace": "Symfony\\Component\\HttpKernel",
            "short_class": "Client",
            "class": "Symfony\\Component\\HttpKernel\\Client",
            "type": "->",
            "function": "doRequest",
            "file": "\/var\/www\/htdocs\/vendor\/symfony\/framework-bundle\/Client.php",
            "line": 131,
            "args": [
              [
                "object",
                "Symfony\\Component\\HttpFoundation\\Request"
              ]
            ]
          },
          {
            "namespace": "Symfony\\Bundle\\FrameworkBundle",
            "short_class": "Client",
            "class": "Symfony\\Bundle\\FrameworkBundle\\Client",
            "type": "->",
            "function": "doRequest",
            "file": "\/var\/www\/htdocs\/vendor\/symfony\/browser-kit\/Client.php",
            "line": 407,
            "args": [
              [
                "object",
                "Symfony\\Component\\HttpFoundation\\Request"
              ]
            ]
          },
          {
            "namespace": "Symfony\\Component\\BrowserKit",
            "short_class": "Client",
            "class": "Symfony\\Component\\BrowserKit\\Client",
            "type": "->",
            "function": "request",
            "file": "\/var\/www\/htdocs\/tests\/DTSApiTestCase.php",
            "line": 25,
            "args": [
              [
                "string",
                "PUT"
              ],
              [
                "string",
                "http:\/\/localhost\/api\/stores\/21"
              ],
              [
                "array",
                []
              ],
              [
                "array",
                []
              ],
              [
                "array",
                {
                  "HTTP_USER_AGENT": [
                    "string",
                    "Symfony BrowserKit"
                  ],
                  "HTTP_ACCEPT": [
                    "string",
                    "application\/json"
                  ],
                  "HTTP_Authorization": [
                    "string",
                    "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1NzA2NTY0MTgsImV4cCI6MTU3MTI2MTIxOCwicm9sZXMiOlsiUk9MRV9PUFRJQ0lBTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6Im9wdGlAdGVzdC5jb20ifQ.akXw59nL0Hza3rD8IZN-xpzjDNBvdpghg_ETKdDQ12oxteliT4eBf_yN4phl5BbP4UgF869i0N3fqW2hDft8v6RYgLsrJ3QBicww_ZODtUOr5YCZQpnrhv7tPw-PHlGIv1pIqVmNnGGy_IyNpmxGJTNwt5J3DaS9dL_lpoytoDqoV1lOw0IJjyjsnvPX8yJ3wsYaYa96UadgXmr-dQ_t-DQKpKnDum4JLD4Q_oTaU0G3wfgVlNg_GXl-Cqa8QFVsM3VrR0SiKvIK5IZeIGkDUGbyB8SAd-zPujcBhM_BREOMLqFWNpLZeNu3bgYuANwnG63oRpp6wUuuGYcmgjqnuswpVJyRuK4_qoOt7U1-rowvC1t4VQW-OoAsj-KiZ2cVsI73CGqoNVUTRbenqJB4XVDDicGbEq9JWgUqeMsZbxdrWSXNBleJAc7u4ZpsCyAedjtDLg_-TNJe_el3rPDibPembjXnZJvl356I0L-xGj10WN5YSgsm_Q-EWJZzaRuWSx5noxjUHzaqTQToiQqSKzCgNepIaUL-RDwVSdzsdtx2LtCt9tNBSMMWpioEBdqOI0bAQmpfy_HIMkxc3d5w9m04aV87Zq4BY14cvMMHhEn322fr2zahK0e4QAnIB6PQh8W1VSo6cbUDSy00ATU4AaREMJSJv7pJ096FxY8yKU4"
                  ],
                  "CONTENT_TYPE": [
                    "string",
                    "application\/json"
                  ],
                  "ACCEPT": [
                    "string",
                    "application\/json"
                  ],
                  "HTTP_REFERER": [
                    "string",
                    "http:\/\/localhost\/api\/login_check"
                  ],
                  "HTTP_HOST": [
                    "string",
                    "localhost"
                  ],
                  "HTTPS": [
                    "boolean",
                    false
                  ]
                }
              ],
              [
                "string",
                "{\n    \"storeAddress\": 1,\n    \"optician\": 1\n}"
              ]
            ]
          },
          {
            "namespace": "Test\\App",
            "short_class": "DTSApiTestCase",
            "class": "Test\\App\\DTSApiTestCase",
            "type": "->",
            "function": "request",
            "file": "\/var\/www\/htdocs\/tests\/Controller\/Store\/StoreControllerTest.php",
            "line": 40,
            "args": [
              [
                "string",
                "PUT"
              ],
              [
                "string",
                "\/api\/stores\/21"
              ],
              [
                "array",
                []
              ],
              [
                "array",
                []
              ],
              [
                "array",
                []
              ],
              [
                "string",
                "{\n    \"storeAddress\": 1,\n    \"optician\": 1\n}"
              ]
            ]
          },
          {
            "namespace": "Test\\App\\Controller\\Store",
            "short_class": "StoreControllerTest",
            "class": "Test\\App\\Controller\\StoreControllerTest",
            "type": "->",
            "function": "testUpdateStore",
            "file": "\/var\/www\/htdocs\/vendor\/phpunit\/phpunit\/src\/Framework\/TestCase.php",
            "line": 1328,
            "args": []
          },
          {
            "namespace": "PHPUnit\\Framework",
            "short_class": "TestCase",
            "class": "PHPUnit\\Framework\\TestCase",
            "type": "->",
            "function": "runTest",
            "file": "\/var\/www\/htdocs\/vendor\/phpunit\/phpunit\/src\/Framework\/TestCase.php",
            "line": 948,
            "args": []
          },
          {
            "namespace": "PHPUnit\\Framework",
            "short_class": "TestCase",
            "class": "PHPUnit\\Framework\\TestCase",
            "type": "->",
            "function": "runBare",
            "file": "\/var\/www\/htdocs\/vendor\/phpunit\/phpunit\/src\/Framework\/TestResult.php",
            "line": 680,
            "args": []
          },
          {
            "namespace": "PHPUnit\\Framework",
            "short_class": "TestResult",
            "class": "PHPUnit\\Framework\\TestResult",
            "type": "->",
            "function": "run",
            "file": "\/var\/www\/htdocs\/vendor\/phpunit\/phpunit\/src\/Framework\/TestCase.php",
            "line": 677,
            "args": [
              [
                "object",
                "Test\\App\\Controller\\StoreControllerTest"
              ]
            ]
          },
          {
            "namespace": "PHPUnit\\Framework",
            "short_class": "TestCase",
            "class": "PHPUnit\\Framework\\TestCase",
            "type": "->",
            "function": "run",
            "file": "\/var\/www\/htdocs\/vendor\/phpunit\/phpunit\/src\/Framework\/TestSuite.php",
            "line": 568,
            "args": [
              [
                "object",
                "PHPUnit\\Framework\\TestResult"
              ]
            ]
          },
          {
            "namespace": "PHPUnit\\Framework",
            "short_class": "TestSuite",
            "class": "PHPUnit\\Framework\\TestSuite",
            "type": "->",
            "function": "run",
            "file": "\/var\/www\/htdocs\/vendor\/phpunit\/phpunit\/src\/TextUI\/TestRunner.php",
            "line": 619,
            "args": [
              [
                "object",
                "PHPUnit\\Framework\\TestResult"
              ]
            ]
          },
          {
            "namespace": "PHPUnit\\TextUI",
            "short_class": "TestRunner",
            "class": "PHPUnit\\TextUI\\TestRunner",
            "type": "->",
            "function": "doRun",
            "file": "\/var\/www\/htdocs\/vendor\/phpunit\/phpunit\/src\/TextUI\/Command.php",
            "line": 201,
            "args": [
              [
                "object",
                "PHPUnit\\Framework\\TestSuite"
              ],
              [
                "array",
                {
                  "listGroups": [
                    "boolean",
                    false
                  ],
                  "listSuites": [
                    "boolean",
                    false
                  ],
                  "listTests": [
                    "boolean",
                    false
                  ],
                  "listTestsXml": [
                    "boolean",
                    false
                  ],
                  "loader": [
                    "null",
                    null
                  ],
                  "useDefaultConfiguration": [
                    "boolean",
                    true
                  ],
                  "loadedExtensions": [
                    "array",
                    []
                  ],
                  "notLoadedExtensions": [
                    "array",
                    []
                  ],
                  "testSuffixes": [
                    "array",
                    [
                      [
                        "string",
                        "Test.php"
                      ],
                      [
                        "string",
                        ".phpt"
                      ]
                    ]
                  ],
                  "configuration": [
                    "object",
                    "PHPUnit\\Util\\Configuration"
                  ],
                  "debug": [
                    "boolean",
                    false
                  ],
                  "filter": [
                    "boolean",
                    false
                  ],
                  "listeners": [
                    "array",
                    []
                  ],
                  "backupGlobals": [
                    "boolean",
                    false
                  ],
                  "bootstrap": [
                    "string",
                    "\/var\/www\/htdocs\/config\/bootstrap.php"
                  ],
                  "colors": [
                    "string",
                    "auto"
                  ],
                  "testdoxGroups": [
                    "array",
                    []
                  ],
                  "testdoxExcludeGroups": [
                    "array",
                    []
                  ],
                  "addUncoveredFilesFromWhitelist": [
                    "boolean",
                    true
                  ],
                  "backupStaticAttributes": [
                    "null",
                    null
                  ],
                  "beStrictAboutChangesToGlobalState": [
                    "null",
                    null
                  ],
                  "beStrictAboutResourceUsageDuringSmallTests": [
                    "boolean",
                    false
                  ],
                  "cacheResult": [
                    "boolean",
                    true
                  ],
                  "cacheTokens": [
                    "boolean",
                    false
                  ],
                  "columns": [
                    "integer",
                    80
                  ],
                  "convertDeprecationsToExceptions": [
                    "boolean",
                    true
                  ],
                  "convertErrorsToExceptions": [
                    "boolean",
                    true
                  ],
                  "convertNoticesToExceptions": [
                    "boolean",
                    true
                  ],
                  "convertWarningsToExceptions": [
                    "boolean",
                    true
                  ],
                  "crap4jThreshold": [
                    "integer",
                    30
                  ],
                  "disallowTestOutput": [
                    "boolean",
                    false
                  ],
                  "disallowTodoAnnotatedTests": [
                    "boolean",
                    false
                  ],
                  "defaultTimeLimit": [
                    "integer",
                    0
                  ],
                  "enforceTimeLimit": [
                    "boolean",
                    false
                  ],
                  "excludeGroups": [
                    "array",
                    []
                  ],
                  "executionOrder": [
                    "integer",
                    0
                  ],
                  "executionOrderDefects": [
                    "integer",
                    0
                  ],
                  "failOnRisky": [
                    "boolean",
                    false
                  ],
                  "failOnWarning": [
                    "boolean",
                    false
                  ],
                  "groups": [
                    "array",
                    []
                  ],
                  "noInteraction": [
                    "boolean",
                    false
                  ],
                  "processIsolation": [
                    "boolean",
                    false
                  ],
                  "processUncoveredFilesFromWhitelist": [
                    "boolean",
                    false
                  ],
                  "randomOrderSeed": [
                    "integer",
                    1570656418
                  ],
                  "registerMockObjectsFromTestArgumentsRecursively": [
                    "boolean",
                    false
                  ],
                  "repeat": [
                    "boolean",
                    false
                  ],
                  "reportHighLowerBound": [
                    "integer",
                    90
                  ],
                  "reportLowUpperBound": [
                    "integer",
                    50
                  ],
                  "reportUselessTests": [
                    "boolean",
                    true
                  ],
                  "reverseList": [
                    "boolean",
                    false
                  ],
                  "resolveDependencies": [
                    "boolean",
                    true
                  ],
                  "stopOnError": [
                    "boolean",
                    false
                  ],
                  "stopOnFailure": [
                    "boolean",
                    false
                  ],
                  "stopOnIncomplete": [
                    "boolean",
                    false
                  ],
                  "stopOnRisky": [
                    "boolean",
                    false
                  ],
                  "stopOnSkipped": [
                    "boolean",
                    false
                  ],
                  "stopOnWarning": [
                    "boolean",
                    false
                  ],
                  "stopOnDefect": [
                    "boolean",
                    false
                  ],
                  "strictCoverage": [
                    "boolean",
                    false
                  ],
                  "timeoutForLargeTests": [
                    "integer",
                    60
                  ],
                  "timeoutForMediumTests": [
                    "integer",
                    10
                  ],
                  "timeoutForSmallTests": [
                    "integer",
                    1
                  ],
                  "verbose": [
                    "boolean",
                    false
                  ],
                  "cacheResultFile": [
                    "string",
                    "\/var\/www\/htdocs"
                  ]
                }
              ],
              [
                "boolean",
                true
              ]
            ]
          },
          {
            "namespace": "PHPUnit\\TextUI",
            "short_class": "Command",
            "class": "PHPUnit\\TextUI\\Command",
            "type": "->",
            "function": "run",
            "file": "\/var\/www\/htdocs\/vendor\/phpunit\/phpunit\/src\/TextUI\/Command.php",
            "line": 160,
            "args": [
              [
                "array",
                [
                  [
                    "string",
                    "vendor\/bin\/phpunit"
                  ],
                  [
                    "string",
                    "tests\/Controller\/Store\/StoreControllerTest.php"
                  ]
                ]
              ],
              [
                "boolean",
                true
              ]
            ]
          },
          {
            "namespace": "PHPUnit\\TextUI",
            "short_class": "Command",
            "class": "PHPUnit\\TextUI\\Command",
            "type": "::",
            "function": "main",
            "file": "\/var\/www\/htdocs\/vendor\/phpunit\/phpunit\/phpunit",
            "line": 61,
            "args": []
          }
        ]
      }
    ]
  }
}
</code>
</pre>
</details>

**Comment by vvasiloi** [comment]
And the routing configuration?

**Comment by mamazu** [comment]
This is the route
```yml
app_stores:
  resource: |
    alias: app.stores
    permission: true
    grid: app_store_grid
    except: [show, create]
  type: sylius.resource_api
```

and the grid is this:
```yml
    app_store_grid:
      driver:
        options:
          class: App\Entity\Store
      fields:
        name:
          type: string
      filters:
        name:
          type: string
          form_options:
            type: contains
```

and the repository is method was not changed. It's the default Sylius repository.

**Comment by Roshyo** [comment]
First, I would change the `App\Entity\Store` into `%app.model.store.class%` or whatever your resource is.

Then I would add `name: doctrine/orm` under `driver` in the grid. Not sure it's not needed nor by default though.

**Comment by mamazu** [comment]
I did what you said but it didn't fix the problem.

**Comment by loic425** [comment]
I know this is an old issue but the factory config here is wrong.
```
sylius_resource:
    app.store:
        classes:
            model: 'App\Entity\Store'
            repository: 'App\Repository\StoreRepository'
```
You can remove your factory. By default it uses Sylius\Component\Resource\Factory\Factory as factory. You can use an entity as a factory. It should implements FactoryInterface.

**Comment by mamazu** [comment]
Yeah, I know but we need more functionality on the factory (like different ways to construct the object). And the factory does implement the required Interface.

**Comment by loic425** [comment]
Yes in this case, you should create your own factory. Decoration method is better.

config/services.yaml
```
    App\Factory\StoreFactory:
        decorates: 'app.factory.store'
        arguments:
            $factory: '@App\Factory\StoreFactory.inner'
```

**Comment by mamazu** [comment]
But this would mean I'd need to proxy all the methods from the Sylius Factory to the outer factory.

**Comment by vvasiloi** [comment]
@mamazu there's only one method: `createNew`

**Comment by mamazu** [comment]
But for extensibilty this might not be the thing I want. And the factory is not the problem.

**Comment by vvasiloi** [comment]
Whether you decorate the default factory or not, the custom factory must implement the `FactoryInterface` and the `createNew` method.

**Comment by mamazu** [comment]
True, and it does.

**Comment by vvasiloi** [comment]
Do you still have the issue and want to fix it?

**Comment by mamazu** [comment]
Well I fixed it by overriding the class resolution logic but I think this is either wrong or something that needs to be pull requested.

**Comment by vvasiloi** [comment]
Well, we didn't identify an issue here and there's not enough context to do so.
Can you reproduce it in a project built from scratch and publish it in a public repository?

**Comment by mamazu** [comment]
Good idea. I will try that tomorrow.
