### ISSUE TITLE
Symfony 5 support

### ISSUE THREAD

**Issue by pamil** [Sylius/SyliusResourceBundle#121]
The issue to track and coordinate efforts.

**Comment by Roshyo** [comment]
Where are we on this ?

**Comment by loic425** [comment]
Can we help on something?

**Comment by pamil** [comment]
There's no work done yet, I'd start from adding a line to `.travis.yml` with `SYMFONY_VERSION=5.0.*`, allowing for Symfony ^5.0 components in `composer.json` and running the tests.

**Comment by loic425** [comment]
@pamil I want to help finishing that big work, but some PR are still on review on SyliusResourceBundle.

**Comment by alexsoftdev** [comment]
Any news about sf5?

**Comment by loic425** [comment]
> Any news about sf5?

it supports Symfony 5 since 1.7.x
