### ISSUE TITLE
LogicException when submitting invalid (empty) fields for resource creation

### ISSUE THREAD

**Issue by rimas-kudelis** [Sylius/SyliusResourceBundle#171]
When I make a POST request with invalid POST data to `/LOCALE/account/address-book/add`, I'm getting a 500 response and a LogicException saying "Cannot check if an unsubmitted form is valid. Call Form::isSubmitted() before Form::isValid().".

This appears to be caused by [line 188 in ResourceController.php](https://github.com/Sylius/SyliusResourceBundle/blob/bba7e56ad60d05ce8884e1aa7ac8874abed7ad1f/src/Bundle/Controller/ResourceController.php#L188), which reads as follows:
```
if ($request->isMethod('POST') && $form->handleRequest($request)->isValid()) {
```
Is there a reason why the `isSubmitted()` check is not performed here?

**Comment by loic425** [comment]
Yes I've already seen this error years ago.

On symfony demo:
`if ($form->isSubmitted() && $form->isValid()) {`
https://github.com/symfony/demo/blob/master/src/Controller/BlogController.php#L103

**Comment by loic425** [comment]
@pamil @lchrusciel  I opened a pull request to fix this error.
