### ISSUE TITLE
Non-existent parameter "sylius.doctrine.orm.container_repository_factory.entities"

### ISSUE THREAD

**Issue by pdias** [Sylius/SyliusResourceBundle#233]
I have update and now i have this error:

**Sylius version affected**: dev-master

`Script cache:clear returned with error code 1
!!
!!  In DefinitionErrorExceptionPass.php line 54:
!!
!!    You have requested a non-existent parameter "sylius.doctrine.orm.container_repository_factory.entities".`

**Comment by chellem** [comment]
Same problem here.

@pdias have you discover any solution ?

Seems like a parameter has to be defined.

**Comment by pdias** [comment]
I made some changes in **Sylius\Bundle\ResourceBundle\DependencyInjection\Driver\Doctrine\DoctrineORMDriver** and I don't know if it's a good solution, but it works.

`protected function addRepository(ContainerBuilder $container, MetadataInterface $metadata): void
    {
        $repositoryClassParameterName = sprintf('%s.repository.%s.class', $metadata->getApplicationName(), $metadata->getName());
        $repositoryClass = EntityRepository::class;

        if ($container->hasParameter($repositoryClassParameterName)) {
            $repositoryClass = $container->getParameter($repositoryClassParameterName);
        }

        if ($metadata->hasClass('repository')) {
            $repositoryClass = $metadata->getClass('repository');
        }

        $serviceId = $metadata->getServiceId('repository');
        $managerReference = new Reference($metadata->getServiceId('manager'));
        $definition = new Definition($repositoryClass);
        $definition->setPublic(true);

        $genericEntitiesParameterName = 'sylius.doctrine.orm.container_repository_factory.entities';
        $genericEntities = $container->hasParameter($genericEntitiesParameterName) ? $container->getParameter($genericEntitiesParameterName) : [];
        $container->setParameter($genericEntitiesParameterName, $genericEntities);

        if ($repositoryClass === EntityRepository::class) {
            $entityClass = $metadata->getClass('model');

            $definition->setFactory([$managerReference, 'getRepository']);
            $definition->setArguments([$entityClass]);

            $container->setDefinition($serviceId, $definition);

            //$genericEntitiesParameterName = 'sylius.doctrine.orm.container_repository_factory.entities';
            //$genericEntities = $container->hasParameter($genericEntitiesParameterName) ? $container->getParameter($genericEntitiesParameterName) : [];

            $genericEntities[] = $entityClass;
            $container->setParameter($genericEntitiesParameterName, $genericEntities);
        } else {
            $definition->setArguments([$managerReference, $this->getClassMetadataDefinition($metadata)]);

            $container->setDefinition($serviceId, $definition);

            $doctrineDefinition = new Definition($repositoryClass);
            $doctrineDefinition->addTag(ServiceRepositoryCompilerPass::REPOSITORY_SERVICE_TAG);
            $doctrineDefinition->setFactory([new Reference('service_container'), 'get']);
            $doctrineDefinition->setArguments([$serviceId]);

            $container->setDefinition($repositoryClass, $doctrineDefinition);
        }

        $typehintClasses = array_merge(
            class_implements($repositoryClass),
            [$repositoryClass],
            class_parents($repositoryClass)
        );

        foreach ($typehintClasses as $typehintClass) {
            $container->registerAliasForArgument(
                $metadata->getServiceId('repository'),
                $typehintClass,
                $metadata->getHumanizedName() . ' repository'
            );
        }
    }`

This way the parameter **sylius.doctrine.orm.container_repository_factory.entities** is always created .

**Comment by pamil** [comment]
It should be already fixed in the newest master, please let me know if anything shows up.
