### ISSUE TITLE
Cannot install : You have requested a non-existent parameter "locale"

### ISSUE THREAD

**Issue by SylvanoTombo** [Sylius/SyliusResourceBundle#244]
**Description**
I've got an error while installing sylius/resource-bundle via composer. When clearing cache after installing dependencies, Composer says :

> Executing script cache:clear [KO]
> [KO]
> Script cache:clear returned with error code 1
> 
> In DefinitionErrorExceptionPass.php line 54:
> 
>`You have requested a non-existent parameter "locale". Did you mean one of these: "kernel.default_locale", "stof_doctrine_extensions.default_locale", "sylius_money.locale"?`

> Script @auto-scripts was called via post-update-cmd
> Installation failed, reverting ./composer.json to its original content.

Steps to reproduce

composer create-project symfony/skeleton symfony && cd symfony
composer require sylius/resource-bundle
Do you want to execute this recipe? : a

**Comment by loic425** [comment]
symfony new acme --version="^4.4"
cd acme;
composer require symfony/orm-pack

Edit this file `config/services.yaml`

```
parameters:
    locale: en
```

composer require sylius/resource-bundle

**Comment by SylvanoTombo** [comment]
@loic425 , Thanks
