### ISSUE TITLE
Double tagging issue with PrioritizedCompositeServicePass

### ISSUE THREAD

**Issue by kayue** [Sylius/SyliusResourceBundle#306]
**Sylius version affected**: 1.8

**Description**  
For example `SyliusOrderExtension::load()`'s autoconfiguration will cause services being tagged twice. It makes developer very difficult to re-prioritze a service.

**Steps to reproduce**  

1. Define a cart context that implement `CartContextInterface`

```
Your\Context\TokenValueBasedCartContext:
        tags:
            - { name: sylius.context.cart, priority: 250 }
```

2. This service will end up having two tag due to `SyliusOrderExtension::load()`'s autoconfiguration.

```
Your\Context\TokenValueBasedCartContext:
        tags:
            - { name: sylius.context.cart, priority: 250 }
            - { name: sylius.context.cart }
```

3. `PrioritizedCompositeServicePass` will add this service twice to the composite service.

**Possible Solution**

**Comment by vvasiloi** [comment]
For anyone else who has this issues gets here, here's how to solve it:
Add `autoconfigure: false` to the service definition.
```
Your\Context\TokenValueBasedCartContext:
    autoconfigure: false
    tags:
        - { name: sylius.context.cart, priority: 250 }
        - { name: sylius.context.cart }
```
