### ISSUE TITLE
Change deprecations

### ISSUE THREAD

**Issue by dannyvw** [Sylius/SyliusResourceBundle#448]
Can we change some deprecations? Deprecations like this are rendered on each page but we can't solve them

https://github.com/Sylius/SyliusResourceBundle/blob/1.10/src/Bundle/DependencyInjection/PagerfantaExtension.php#L20
https://github.com/Sylius/SyliusResourceBundle/blob/1.10/src/Bundle/DependencyInjection/PagerfantaConfiguration.php#L20
https://github.com/Sylius/SyliusResourceBundle/blob/1.10/src/Bundle/DependencyInjection/Compiler/PagerfantaBridgePass.php#L20
https://github.com/Sylius/SyliusResourceBundle/blob/1.10/src/Bundle/DependencyInjection/Driver/Doctrine/DoctrineODMDriver.php#L25
https://github.com/Sylius/SyliusResourceBundle/blob/1.10/src/Bundle/DependencyInjection/Driver/Doctrine/DoctrinePHPCRDriver.php#L27

**Comment by Roshyo** [comment]
Well, deprecations are only for debug mode, so it won't affect your production setup.
And removing them would probably mean forgetting them, so I believe we should keep them and fix them as soon we can.

**Comment by dannyvw** [comment]
These deprecations "pollute" the overview so you have to read through the same deprecations every time to see if they can be solved. Hence the question whether we can adjust this. Otherwise this can be closed.

**Comment by mbabker** [comment]
#450 could improve this a bit, especially for the unfixable deprecations.
