### ISSUE TITLE
Symfony 6.1 form submit error

### ISSUE THREAD

**Issue by dannyvw** [Sylius/SyliusResourceBundle#475]
**Sylius version affected**: v1.10.0-ALPHA.1 

**Description**  
With Symfony 6.1 forms cannot be submitted due to this error "Input value "form" contains a non-scalar value.". When debugging the value inside InputBag contains an array with all form fields.

This was the deprecation before:

```
User Deprecated: Since symfony/http-foundation 5.1: Retrieving a non-string value from "Symfony\Component\HttpFoundation\InputBag::get()" is deprecated, and will throw a "Symfony\Component\HttpFoundation\Exception\BadRequestException" exception in Symfony 6.0, use "Symfony\Component\HttpFoundation\InputBag::all($key)" instead.

class: HttpFoundationRequestHandler, line 88
```

**Possible Solution**  

Change https://github.com/Sylius/SyliusResourceBundle/blob/v1.10.0-ALPHA.1/src/Bundle/Form/Extension/HttpFoundation/HttpFoundationRequestHandler.php#L89 too
```
$params = $request->request->all($name); or $params = $request->request->all()[$name]
```

**Comment by dannyvw** [comment]
Same issue with the filters

**Comment by loic425** [comment]
Thank you @dannyvw I was aware of this error and I've fixed it in a PR yesterday.
https://github.com/Sylius/SyliusResourceBundle/pull/471
