### ISSUE TITLE
Symfony 6.3 deprecation doctrine subscribers

### ISSUE THREAD

**Issue by dannyvw** [Sylius/SyliusResourceBundle#736]
**Sylius version affected**: > 1.10

**Description**  

User Deprecated: Since symfony/doctrine-bridge 6.3: Using Doctrine subscribers as services is deprecated, declare listeners instead

Deprecation message is triggered for the following classes:
- Sylius\Bundle\ResourceBundle\EventListener\ORMTranslatableListener
- Sylius\Bundle\ResourceBundle\EventListener\ORMRepositoryClassSubscriber
- Sylius\Bundle\ResourceBundle\EventListener\ORMMappedSuperClassSubscriber

**Comment by loic425** [comment]
https://github.com/symfony/symfony/issues/49586
