### ISSUE TITLE
Symfony 7.1 deprecation

### ISSUE THREAD

**Issue by dannyvw** [Sylius/SyliusResourceBundle#946]
**Sylius version affected**: 1.12

**Description**  
The "Symfony\Component\HttpKernel\DependencyInjection\Extension" class is considered internal since Symfony 7.1, to be deprecated in 8.1; use Symfony\Component\DependencyInjection\Extension\Extension instead. It may change without further notice. You should not use it from "Sylius\Bundle\ResourceBundle\DependencyInjection\PagerfantaExtension".

**Steps to reproduce**  

**Possible Solution**

**Comment by loic425** [comment]
Thx, will be fixed in #948
